import type { RawDadObjectInfo } from "../app/data/dadObjects";

/** PLACEHOLDER content — see CONTENT_LICENSE.md. */
export const weekObjects: RawDadObjectInfo[] = [
  { week: 4, assetId: "watch-crown", type: "watch", name: "Sample object 4", nameRo: "Obiect exemplu 4", description: "Sample comparison for week 4.", descriptionRo: "Comparație exemplu pentru săptămâna 4." },
  { week: 5, assetId: "watch-face", type: "watch", name: "Sample object 5", nameRo: "Obiect exemplu 5", description: "Sample comparison for week 5.", descriptionRo: "Comparație exemplu pentru săptămâna 5." },
  { week: 6, assetId: "shirt-button", type: "button", name: "Sample object 6", nameRo: "Obiect exemplu 6", description: "Sample comparison for week 6.", descriptionRo: "Comparație exemplu pentru săptămâna 6." },
  { week: 7, assetId: "small-keyring", type: "key", name: "Sample object 7", nameRo: "Obiect exemplu 7", description: "Sample comparison for week 7.", descriptionRo: "Comparație exemplu pentru săptămâna 7." },
  { week: 8, assetId: "mailbox-key", type: "key", name: "Sample object 8", nameRo: "Obiect exemplu 8", description: "Sample comparison for week 8.", descriptionRo: "Comparație exemplu pentru săptămâna 8." },
  { week: 9, assetId: "ballpoint-pen", type: "pen", name: "Sample object 9", nameRo: "Obiect exemplu 9", description: "Sample comparison for week 9.", descriptionRo: "Comparație exemplu pentru săptămâna 9." },
  { week: 10, assetId: "tape-measure-hook", type: "tape-measure", name: "Sample object 10", nameRo: "Obiect exemplu 10", description: "Sample comparison for week 10.", descriptionRo: "Comparație exemplu pentru săptămâna 10." },
  { week: 11, assetId: "short-tape-measure-pull", type: "tape-measure", name: "Sample object 11", nameRo: "Obiect exemplu 11", description: "Sample comparison for week 11.", descriptionRo: "Comparație exemplu pentru săptămâna 11." },
  { week: 12, assetId: "front-door-lock-cylinder", type: "lock", name: "Sample object 12", nameRo: "Obiect exemplu 12", description: "Sample comparison for week 12.", descriptionRo: "Comparație exemplu pentru săptămâna 12." },
  { week: 13, assetId: "wallet-corner", type: "wallet", name: "Sample object 13", nameRo: "Obiect exemplu 13", description: "Sample comparison for week 13.", descriptionRo: "Comparație exemplu pentru săptămâna 13." },
  { week: 14, assetId: "card-sleeve", type: "wallet", name: "Sample object 14", nameRo: "Obiect exemplu 14", description: "Sample comparison for week 14.", descriptionRo: "Comparație exemplu pentru săptămâna 14." },
  { week: 15, assetId: "folded-wallet", type: "wallet", name: "Sample object 15", nameRo: "Obiect exemplu 15", description: "Sample comparison for week 15.", descriptionRo: "Comparație exemplu pentru săptămâna 15." },
  { week: 16, assetId: "phone-camera-bar", type: "smartphone", name: "Sample object 16", nameRo: "Obiect exemplu 16", description: "Sample comparison for week 16.", descriptionRo: "Comparație exemplu pentru săptămâna 16." },
  { week: 17, assetId: "charging-cable-coil", type: "cable", name: "Sample object 17", nameRo: "Obiect exemplu 17", description: "Sample comparison for week 17.", descriptionRo: "Comparație exemplu pentru săptămâna 17." },
  { week: 18, assetId: "smartphone", type: "smartphone", name: "Sample object 18", nameRo: "Obiect exemplu 18", description: "Sample comparison for week 18.", descriptionRo: "Comparație exemplu pentru săptămâna 18." },
  { week: 19, assetId: "espresso-cup", type: "coffee", name: "Sample object 19", nameRo: "Obiect exemplu 19", description: "Sample comparison for week 19.", descriptionRo: "Comparație exemplu pentru săptămâna 19." },
  { week: 20, assetId: "coffee-mug", type: "coffee", name: "Sample object 20", nameRo: "Obiect exemplu 20", description: "Sample comparison for week 20.", descriptionRo: "Comparație exemplu pentru săptămâna 20." },
  { week: 21, assetId: "travel-mug", type: "coffee", name: "Sample object 21", nameRo: "Obiect exemplu 21", description: "Sample comparison for week 21.", descriptionRo: "Comparație exemplu pentru săptămâna 21." },
  { week: 22, assetId: "pocket-notebook", type: "notebook", name: "Sample object 22", nameRo: "Obiect exemplu 22", description: "Sample comparison for week 22.", descriptionRo: "Comparație exemplu pentru săptămâna 22." },
  { week: 23, assetId: "notebook-spine", type: "notebook", name: "Sample object 23", nameRo: "Obiect exemplu 23", description: "Sample comparison for week 23.", descriptionRo: "Comparație exemplu pentru săptămâna 23." },
  { week: 24, assetId: "desk-notebook", type: "notebook", name: "Sample object 24", nameRo: "Obiect exemplu 24", description: "Sample comparison for week 24.", descriptionRo: "Comparație exemplu pentru săptămâna 24." },
  { week: 25, assetId: "folded-tie", type: "tie", name: "Sample object 25", nameRo: "Obiect exemplu 25", description: "Sample comparison for week 25.", descriptionRo: "Comparație exemplu pentru săptămâna 25." },
  { week: 26, assetId: "rolled-belt", type: "belt", name: "Sample object 26", nameRo: "Obiect exemplu 26", description: "Sample comparison for week 26.", descriptionRo: "Comparație exemplu pentru săptămâna 26." },
  { week: 27, assetId: "folded-newspaper", type: "newspaper", name: "Sample object 27", nameRo: "Obiect exemplu 27", description: "Sample comparison for week 27.", descriptionRo: "Comparație exemplu pentru săptămâna 27." },
  { week: 28, assetId: "sunglasses", type: "sunglasses", name: "Sample object 28", nameRo: "Obiect exemplu 28", description: "Sample comparison for week 28.", descriptionRo: "Comparație exemplu pentru săptămâna 28." },
  { week: 29, assetId: "compact-umbrella", type: "umbrella", name: "Sample object 29", nameRo: "Obiect exemplu 29", description: "Sample comparison for week 29.", descriptionRo: "Comparație exemplu pentru săptămâna 29." },
  { week: 30, assetId: "laptop-charger-with-cable", type: "charger", name: "Sample object 30", nameRo: "Obiect exemplu 30", description: "Sample comparison for week 30.", descriptionRo: "Comparație exemplu pentru săptămâna 30." },
  { week: 31, assetId: "multitool", type: "tool", name: "Sample object 31", nameRo: "Obiect exemplu 31", description: "Sample comparison for week 31.", descriptionRo: "Comparație exemplu pentru săptămâna 31." },
  { week: 32, assetId: "full-screwdriver", type: "tool", name: "Sample object 32", nameRo: "Obiect exemplu 32", description: "Sample comparison for week 32.", descriptionRo: "Comparație exemplu pentru săptămâna 32." },
  { week: 33, assetId: "socket-wrench", type: "tool", name: "Sample object 33", nameRo: "Obiect exemplu 33", description: "Sample comparison for week 33.", descriptionRo: "Comparație exemplu pentru săptămâna 33." },
  { week: 34, assetId: "flashlight", type: "tool", name: "Sample object 34", nameRo: "Obiect exemplu 34", description: "Sample comparison for week 34.", descriptionRo: "Comparație exemplu pentru săptămâna 34." },
  { week: 35, assetId: "power-bank", type: "power-bank", name: "Sample object 35", nameRo: "Obiect exemplu 35", description: "Sample comparison for week 35.", descriptionRo: "Comparație exemplu pentru săptămâna 35." },
  { week: 36, assetId: "gym-water-bottle", type: "water-bottle", name: "Sample object 36", nameRo: "Obiect exemplu 36", description: "Sample comparison for week 36.", descriptionRo: "Comparație exemplu pentru săptămâna 36." },
  { week: 37, assetId: "small-toolbox", type: "toolbox", name: "Sample object 37", nameRo: "Obiect exemplu 37", description: "Sample comparison for week 37.", descriptionRo: "Comparație exemplu pentru săptămâna 37." },
  { week: 38, assetId: "toolbox-handle", type: "toolbox", name: "Sample object 38", nameRo: "Obiect exemplu 38", description: "Sample comparison for week 38.", descriptionRo: "Comparație exemplu pentru săptămâna 38." },
  { week: 39, assetId: "desk-lamp-head", type: "lamp", name: "Sample object 39", nameRo: "Obiect exemplu 39", description: "Sample comparison for week 39.", descriptionRo: "Comparație exemplu pentru săptămâna 39." },
  { week: 40, assetId: "dad-backpack", type: "backpack", name: "Sample object 40", nameRo: "Obiect exemplu 40", description: "Sample comparison for week 40.", descriptionRo: "Comparație exemplu pentru săptămâna 40." },
];
