/**
 * PLACEHOLDER Romanian strings for the sample content.
 * The real translations are proprietary — see CONTENT_LICENSE.md.
 */
export const RO_TEXT: Record<string, string> = {
  "Sample size comparison for week 4.": "Comparație de mărime (exemplu) pentru săptămâna 4.",
  "Sample placeholder summary for week 4. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 4. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 4)": "Reper exemplu A (săptămâna 4)",
  "Sample milestone B (week 4)": "Reper exemplu B (săptămâna 4)",
  "Sample physical note (week 4)": "Notă fizică exemplu (săptămâna 4)",
  "Sample emotional note (week 4)": "Notă emoțională exemplu (săptămâna 4)",
  "Sample dad action 1 (week 4)": "Acțiune exemplu 1 pentru tata (săptămâna 4)",
  "Sample dad action 2 (week 4)": "Acțiune exemplu 2 pentru tata (săptămâna 4)",
  "Sample dad action 3 (week 4)": "Acțiune exemplu 3 pentru tata (săptămâna 4)",
  "Sample heads-up text for week 4.": "Text exemplu „atenție la” pentru săptămâna 4.",
  "Sample tip for dads in week 4.": "Sfat exemplu pentru tați, săptămâna 4.",
  "Tiny shot glass": "Tiny shot glass",
  "Sample size comparison for week 5.": "Comparație de mărime (exemplu) pentru săptămâna 5.",
  "Sample placeholder summary for week 5. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 5. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 5)": "Reper exemplu A (săptămâna 5)",
  "Sample milestone B (week 5)": "Reper exemplu B (săptămâna 5)",
  "Sample physical note (week 5)": "Notă fizică exemplu (săptămâna 5)",
  "Sample emotional note (week 5)": "Notă emoțională exemplu (săptămâna 5)",
  "Sample dad action 1 (week 5)": "Acțiune exemplu 1 pentru tata (săptămâna 5)",
  "Sample dad action 2 (week 5)": "Acțiune exemplu 2 pentru tata (săptămâna 5)",
  "Sample dad action 3 (week 5)": "Acțiune exemplu 3 pentru tata (săptămâna 5)",
  "Sample heads-up text for week 5.": "Text exemplu „atenție la” pentru săptămâna 5.",
  "Sample tip for dads in week 5.": "Sfat exemplu pentru tați, săptămâna 5.",
  "Sample size comparison for week 6.": "Comparație de mărime (exemplu) pentru săptămâna 6.",
  "Sample placeholder summary for week 6. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 6. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 6)": "Reper exemplu A (săptămâna 6)",
  "Sample milestone B (week 6)": "Reper exemplu B (săptămâna 6)",
  "Sample physical note (week 6)": "Notă fizică exemplu (săptămâna 6)",
  "Sample emotional note (week 6)": "Notă emoțională exemplu (săptămâna 6)",
  "Sample dad action 1 (week 6)": "Acțiune exemplu 1 pentru tata (săptămâna 6)",
  "Sample dad action 2 (week 6)": "Acțiune exemplu 2 pentru tata (săptămâna 6)",
  "Sample dad action 3 (week 6)": "Acțiune exemplu 3 pentru tata (săptămâna 6)",
  "Sample heads-up text for week 6.": "Text exemplu „atenție la” pentru săptămâna 6.",
  "Sample tip for dads in week 6.": "Sfat exemplu pentru tați, săptămâna 6.",
  "Sample size comparison for week 7.": "Comparație de mărime (exemplu) pentru săptămâna 7.",
  "Sample placeholder summary for week 7. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 7. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 7)": "Reper exemplu A (săptămâna 7)",
  "Sample milestone B (week 7)": "Reper exemplu B (săptămâna 7)",
  "Sample physical note (week 7)": "Notă fizică exemplu (săptămâna 7)",
  "Sample emotional note (week 7)": "Notă emoțională exemplu (săptămâna 7)",
  "Sample dad action 1 (week 7)": "Acțiune exemplu 1 pentru tata (săptămâna 7)",
  "Sample dad action 2 (week 7)": "Acțiune exemplu 2 pentru tata (săptămâna 7)",
  "Sample dad action 3 (week 7)": "Acțiune exemplu 3 pentru tata (săptămâna 7)",
  "Sample heads-up text for week 7.": "Text exemplu „atenție la” pentru săptămâna 7.",
  "Sample tip for dads in week 7.": "Sfat exemplu pentru tați, săptămâna 7.",
  "Sample size comparison for week 8.": "Comparație de mărime (exemplu) pentru săptămâna 8.",
  "Sample placeholder summary for week 8. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 8. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 8)": "Reper exemplu A (săptămâna 8)",
  "Sample milestone B (week 8)": "Reper exemplu B (săptămâna 8)",
  "Sample physical note (week 8)": "Notă fizică exemplu (săptămâna 8)",
  "Sample emotional note (week 8)": "Notă emoțională exemplu (săptămâna 8)",
  "Sample dad action 1 (week 8)": "Acțiune exemplu 1 pentru tata (săptămâna 8)",
  "Sample dad action 2 (week 8)": "Acțiune exemplu 2 pentru tata (săptămâna 8)",
  "Sample dad action 3 (week 8)": "Acțiune exemplu 3 pentru tata (săptămâna 8)",
  "Sample heads-up text for week 8.": "Text exemplu „atenție la” pentru săptămâna 8.",
  "Sample tip for dads in week 8.": "Sfat exemplu pentru tați, săptămâna 8.",
  "Sample size comparison for week 9.": "Comparație de mărime (exemplu) pentru săptămâna 9.",
  "Sample placeholder summary for week 9. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 9. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 9)": "Reper exemplu A (săptămâna 9)",
  "Sample milestone B (week 9)": "Reper exemplu B (săptămâna 9)",
  "Sample physical note (week 9)": "Notă fizică exemplu (săptămâna 9)",
  "Sample emotional note (week 9)": "Notă emoțională exemplu (săptămâna 9)",
  "Sample dad action 1 (week 9)": "Acțiune exemplu 1 pentru tata (săptămâna 9)",
  "Sample dad action 2 (week 9)": "Acțiune exemplu 2 pentru tata (săptămâna 9)",
  "Sample dad action 3 (week 9)": "Acțiune exemplu 3 pentru tata (săptămâna 9)",
  "Sample heads-up text for week 9.": "Text exemplu „atenție la” pentru săptămâna 9.",
  "Sample tip for dads in week 9.": "Sfat exemplu pentru tați, săptămâna 9.",
  "Cordial glass": "Cordial glass",
  "Sample size comparison for week 10.": "Comparație de mărime (exemplu) pentru săptămâna 10.",
  "Sample placeholder summary for week 10. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 10. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 10)": "Reper exemplu A (săptămâna 10)",
  "Sample milestone B (week 10)": "Reper exemplu B (săptămâna 10)",
  "Sample physical note (week 10)": "Notă fizică exemplu (săptămâna 10)",
  "Sample emotional note (week 10)": "Notă emoțională exemplu (săptămâna 10)",
  "Sample dad action 1 (week 10)": "Acțiune exemplu 1 pentru tata (săptămâna 10)",
  "Sample dad action 2 (week 10)": "Acțiune exemplu 2 pentru tata (săptămâna 10)",
  "Sample dad action 3 (week 10)": "Acțiune exemplu 3 pentru tata (săptămâna 10)",
  "Sample heads-up text for week 10.": "Text exemplu „atenție la” pentru săptămâna 10.",
  "Sample tip for dads in week 10.": "Sfat exemplu pentru tați, săptămâna 10.",
  "Sample size comparison for week 11.": "Comparație de mărime (exemplu) pentru săptămâna 11.",
  "Sample placeholder summary for week 11. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 11. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 11)": "Reper exemplu A (săptămâna 11)",
  "Sample milestone B (week 11)": "Reper exemplu B (săptămâna 11)",
  "Sample physical note (week 11)": "Notă fizică exemplu (săptămâna 11)",
  "Sample emotional note (week 11)": "Notă emoțională exemplu (săptămâna 11)",
  "Sample dad action 1 (week 11)": "Acțiune exemplu 1 pentru tata (săptămâna 11)",
  "Sample dad action 2 (week 11)": "Acțiune exemplu 2 pentru tata (săptămâna 11)",
  "Sample dad action 3 (week 11)": "Acțiune exemplu 3 pentru tata (săptămâna 11)",
  "Sample heads-up text for week 11.": "Text exemplu „atenție la” pentru săptămâna 11.",
  "Sample tip for dads in week 11.": "Sfat exemplu pentru tați, săptămâna 11.",
  "Sample size comparison for week 12.": "Comparație de mărime (exemplu) pentru săptămâna 12.",
  "Sample placeholder summary for week 12. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 12. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 12)": "Reper exemplu A (săptămâna 12)",
  "Sample milestone B (week 12)": "Reper exemplu B (săptămâna 12)",
  "Sample physical note (week 12)": "Notă fizică exemplu (săptămâna 12)",
  "Sample emotional note (week 12)": "Notă emoțională exemplu (săptămâna 12)",
  "Sample dad action 1 (week 12)": "Acțiune exemplu 1 pentru tata (săptămâna 12)",
  "Sample dad action 2 (week 12)": "Acțiune exemplu 2 pentru tata (săptămâna 12)",
  "Sample dad action 3 (week 12)": "Acțiune exemplu 3 pentru tata (săptămâna 12)",
  "Sample heads-up text for week 12.": "Text exemplu „atenție la” pentru săptămâna 12.",
  "Sample tip for dads in week 12.": "Sfat exemplu pentru tați, săptămâna 12.",
  "Sample size comparison for week 13.": "Comparație de mărime (exemplu) pentru săptămâna 13.",
  "Sample placeholder summary for week 13. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 13. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 13)": "Reper exemplu A (săptămâna 13)",
  "Sample milestone B (week 13)": "Reper exemplu B (săptămâna 13)",
  "Sample physical note (week 13)": "Notă fizică exemplu (săptămâna 13)",
  "Sample emotional note (week 13)": "Notă emoțională exemplu (săptămâna 13)",
  "Sample dad action 1 (week 13)": "Acțiune exemplu 1 pentru tata (săptămâna 13)",
  "Sample dad action 2 (week 13)": "Acțiune exemplu 2 pentru tata (săptămâna 13)",
  "Sample dad action 3 (week 13)": "Acțiune exemplu 3 pentru tata (săptămâna 13)",
  "Sample heads-up text for week 13.": "Text exemplu „atenție la” pentru săptămâna 13.",
  "Sample tip for dads in week 13.": "Sfat exemplu pentru tați, săptămâna 13.",
  "Sample size comparison for week 14.": "Comparație de mărime (exemplu) pentru săptămâna 14.",
  "Sample placeholder summary for week 14. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 14. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 14)": "Reper exemplu A (săptămâna 14)",
  "Sample milestone B (week 14)": "Reper exemplu B (săptămâna 14)",
  "Sample physical note (week 14)": "Notă fizică exemplu (săptămâna 14)",
  "Sample emotional note (week 14)": "Notă emoțională exemplu (săptămâna 14)",
  "Sample dad action 1 (week 14)": "Acțiune exemplu 1 pentru tata (săptămâna 14)",
  "Sample dad action 2 (week 14)": "Acțiune exemplu 2 pentru tata (săptămâna 14)",
  "Sample dad action 3 (week 14)": "Acțiune exemplu 3 pentru tata (săptămâna 14)",
  "Sample heads-up text for week 14.": "Text exemplu „atenție la” pentru săptămâna 14.",
  "Sample tip for dads in week 14.": "Sfat exemplu pentru tați, săptămâna 14.",
  "Rocks glass": "Rocks glass",
  "Sample size comparison for week 15.": "Comparație de mărime (exemplu) pentru săptămâna 15.",
  "Sample placeholder summary for week 15. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 15. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 15)": "Reper exemplu A (săptămâna 15)",
  "Sample milestone B (week 15)": "Reper exemplu B (săptămâna 15)",
  "Sample physical note (week 15)": "Notă fizică exemplu (săptămâna 15)",
  "Sample emotional note (week 15)": "Notă emoțională exemplu (săptămâna 15)",
  "Sample dad action 1 (week 15)": "Acțiune exemplu 1 pentru tata (săptămâna 15)",
  "Sample dad action 2 (week 15)": "Acțiune exemplu 2 pentru tata (săptămâna 15)",
  "Sample dad action 3 (week 15)": "Acțiune exemplu 3 pentru tata (săptămâna 15)",
  "Sample heads-up text for week 15.": "Text exemplu „atenție la” pentru săptămâna 15.",
  "Sample tip for dads in week 15.": "Sfat exemplu pentru tați, săptămâna 15.",
  "Sample size comparison for week 16.": "Comparație de mărime (exemplu) pentru săptămâna 16.",
  "Sample placeholder summary for week 16. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 16. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 16)": "Reper exemplu A (săptămâna 16)",
  "Sample milestone B (week 16)": "Reper exemplu B (săptămâna 16)",
  "Sample physical note (week 16)": "Notă fizică exemplu (săptămâna 16)",
  "Sample emotional note (week 16)": "Notă emoțională exemplu (săptămâna 16)",
  "Sample dad action 1 (week 16)": "Acțiune exemplu 1 pentru tata (săptămâna 16)",
  "Sample dad action 2 (week 16)": "Acțiune exemplu 2 pentru tata (săptămâna 16)",
  "Sample dad action 3 (week 16)": "Acțiune exemplu 3 pentru tata (săptămâna 16)",
  "Sample heads-up text for week 16.": "Text exemplu „atenție la” pentru săptămâna 16.",
  "Sample tip for dads in week 16.": "Sfat exemplu pentru tați, săptămâna 16.",
  "Sample size comparison for week 17.": "Comparație de mărime (exemplu) pentru săptămâna 17.",
  "Sample placeholder summary for week 17. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 17. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 17)": "Reper exemplu A (săptămâna 17)",
  "Sample milestone B (week 17)": "Reper exemplu B (săptămâna 17)",
  "Sample physical note (week 17)": "Notă fizică exemplu (săptămâna 17)",
  "Sample emotional note (week 17)": "Notă emoțională exemplu (săptămâna 17)",
  "Sample dad action 1 (week 17)": "Acțiune exemplu 1 pentru tata (săptămâna 17)",
  "Sample dad action 2 (week 17)": "Acțiune exemplu 2 pentru tata (săptămâna 17)",
  "Sample dad action 3 (week 17)": "Acțiune exemplu 3 pentru tata (săptămâna 17)",
  "Sample heads-up text for week 17.": "Text exemplu „atenție la” pentru săptămâna 17.",
  "Sample tip for dads in week 17.": "Sfat exemplu pentru tați, săptămâna 17.",
  "Sample size comparison for week 18.": "Comparație de mărime (exemplu) pentru săptămâna 18.",
  "Sample placeholder summary for week 18. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 18. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 18)": "Reper exemplu A (săptămâna 18)",
  "Sample milestone B (week 18)": "Reper exemplu B (săptămâna 18)",
  "Sample physical note (week 18)": "Notă fizică exemplu (săptămâna 18)",
  "Sample emotional note (week 18)": "Notă emoțională exemplu (săptămâna 18)",
  "Sample dad action 1 (week 18)": "Acțiune exemplu 1 pentru tata (săptămâna 18)",
  "Sample dad action 2 (week 18)": "Acțiune exemplu 2 pentru tata (săptămâna 18)",
  "Sample dad action 3 (week 18)": "Acțiune exemplu 3 pentru tata (săptămâna 18)",
  "Sample heads-up text for week 18.": "Text exemplu „atenție la” pentru săptămâna 18.",
  "Sample tip for dads in week 18.": "Sfat exemplu pentru tați, săptămâna 18.",
  "Sample size comparison for week 19.": "Comparație de mărime (exemplu) pentru săptămâna 19.",
  "Sample placeholder summary for week 19. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 19. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 19)": "Reper exemplu A (săptămâna 19)",
  "Sample milestone B (week 19)": "Reper exemplu B (săptămâna 19)",
  "Sample physical note (week 19)": "Notă fizică exemplu (săptămâna 19)",
  "Sample emotional note (week 19)": "Notă emoțională exemplu (săptămâna 19)",
  "Sample dad action 1 (week 19)": "Acțiune exemplu 1 pentru tata (săptămâna 19)",
  "Sample dad action 2 (week 19)": "Acțiune exemplu 2 pentru tata (săptămâna 19)",
  "Sample dad action 3 (week 19)": "Acțiune exemplu 3 pentru tata (săptămâna 19)",
  "Sample heads-up text for week 19.": "Text exemplu „atenție la” pentru săptămâna 19.",
  "Sample tip for dads in week 19.": "Sfat exemplu pentru tați, săptămâna 19.",
  "Sample size comparison for week 20.": "Comparație de mărime (exemplu) pentru săptămâna 20.",
  "Sample placeholder summary for week 20. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 20. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 20)": "Reper exemplu A (săptămâna 20)",
  "Sample milestone B (week 20)": "Reper exemplu B (săptămâna 20)",
  "Sample physical note (week 20)": "Notă fizică exemplu (săptămâna 20)",
  "Sample emotional note (week 20)": "Notă emoțională exemplu (săptămâna 20)",
  "Sample dad action 1 (week 20)": "Acțiune exemplu 1 pentru tata (săptămâna 20)",
  "Sample dad action 2 (week 20)": "Acțiune exemplu 2 pentru tata (săptămâna 20)",
  "Sample dad action 3 (week 20)": "Acțiune exemplu 3 pentru tata (săptămâna 20)",
  "Sample heads-up text for week 20.": "Text exemplu „atenție la” pentru săptămâna 20.",
  "Sample tip for dads in week 20.": "Sfat exemplu pentru tați, săptămâna 20.",
  "Wine glass": "Wine glass",
  "Sample size comparison for week 21.": "Comparație de mărime (exemplu) pentru săptămâna 21.",
  "Sample placeholder summary for week 21. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 21. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 21)": "Reper exemplu A (săptămâna 21)",
  "Sample milestone B (week 21)": "Reper exemplu B (săptămâna 21)",
  "Sample physical note (week 21)": "Notă fizică exemplu (săptămâna 21)",
  "Sample emotional note (week 21)": "Notă emoțională exemplu (săptămâna 21)",
  "Sample dad action 1 (week 21)": "Acțiune exemplu 1 pentru tata (săptămâna 21)",
  "Sample dad action 2 (week 21)": "Acțiune exemplu 2 pentru tata (săptămâna 21)",
  "Sample dad action 3 (week 21)": "Acțiune exemplu 3 pentru tata (săptămâna 21)",
  "Sample heads-up text for week 21.": "Text exemplu „atenție la” pentru săptămâna 21.",
  "Sample tip for dads in week 21.": "Sfat exemplu pentru tați, săptămâna 21.",
  "Sample size comparison for week 22.": "Comparație de mărime (exemplu) pentru săptămâna 22.",
  "Sample placeholder summary for week 22. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 22. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 22)": "Reper exemplu A (săptămâna 22)",
  "Sample milestone B (week 22)": "Reper exemplu B (săptămâna 22)",
  "Sample physical note (week 22)": "Notă fizică exemplu (săptămâna 22)",
  "Sample emotional note (week 22)": "Notă emoțională exemplu (săptămâna 22)",
  "Sample dad action 1 (week 22)": "Acțiune exemplu 1 pentru tata (săptămâna 22)",
  "Sample dad action 2 (week 22)": "Acțiune exemplu 2 pentru tata (săptămâna 22)",
  "Sample dad action 3 (week 22)": "Acțiune exemplu 3 pentru tata (săptămâna 22)",
  "Sample heads-up text for week 22.": "Text exemplu „atenție la” pentru săptămâna 22.",
  "Sample tip for dads in week 22.": "Sfat exemplu pentru tați, săptămâna 22.",
  "Sample size comparison for week 23.": "Comparație de mărime (exemplu) pentru săptămâna 23.",
  "Sample placeholder summary for week 23. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 23. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 23)": "Reper exemplu A (săptămâna 23)",
  "Sample milestone B (week 23)": "Reper exemplu B (săptămâna 23)",
  "Sample physical note (week 23)": "Notă fizică exemplu (săptămâna 23)",
  "Sample emotional note (week 23)": "Notă emoțională exemplu (săptămâna 23)",
  "Sample dad action 1 (week 23)": "Acțiune exemplu 1 pentru tata (săptămâna 23)",
  "Sample dad action 2 (week 23)": "Acțiune exemplu 2 pentru tata (săptămâna 23)",
  "Sample dad action 3 (week 23)": "Acțiune exemplu 3 pentru tata (săptămâna 23)",
  "Sample heads-up text for week 23.": "Text exemplu „atenție la” pentru săptămâna 23.",
  "Sample tip for dads in week 23.": "Sfat exemplu pentru tați, săptămâna 23.",
  "Sample size comparison for week 24.": "Comparație de mărime (exemplu) pentru săptămâna 24.",
  "Sample placeholder summary for week 24. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 24. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 24)": "Reper exemplu A (săptămâna 24)",
  "Sample milestone B (week 24)": "Reper exemplu B (săptămâna 24)",
  "Sample physical note (week 24)": "Notă fizică exemplu (săptămâna 24)",
  "Sample emotional note (week 24)": "Notă emoțională exemplu (săptămâna 24)",
  "Sample dad action 1 (week 24)": "Acțiune exemplu 1 pentru tata (săptămâna 24)",
  "Sample dad action 2 (week 24)": "Acțiune exemplu 2 pentru tata (săptămâna 24)",
  "Sample dad action 3 (week 24)": "Acțiune exemplu 3 pentru tata (săptămâna 24)",
  "Sample heads-up text for week 24.": "Text exemplu „atenție la” pentru săptămâna 24.",
  "Sample tip for dads in week 24.": "Sfat exemplu pentru tați, săptămâna 24.",
  "Sample size comparison for week 25.": "Comparație de mărime (exemplu) pentru săptămâna 25.",
  "Sample placeholder summary for week 25. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 25. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 25)": "Reper exemplu A (săptămâna 25)",
  "Sample milestone B (week 25)": "Reper exemplu B (săptămâna 25)",
  "Sample physical note (week 25)": "Notă fizică exemplu (săptămâna 25)",
  "Sample emotional note (week 25)": "Notă emoțională exemplu (săptămâna 25)",
  "Sample dad action 1 (week 25)": "Acțiune exemplu 1 pentru tata (săptămâna 25)",
  "Sample dad action 2 (week 25)": "Acțiune exemplu 2 pentru tata (săptămâna 25)",
  "Sample dad action 3 (week 25)": "Acțiune exemplu 3 pentru tata (săptămâna 25)",
  "Sample heads-up text for week 25.": "Text exemplu „atenție la” pentru săptămâna 25.",
  "Sample tip for dads in week 25.": "Sfat exemplu pentru tați, săptămâna 25.",
  "Sample size comparison for week 26.": "Comparație de mărime (exemplu) pentru săptămâna 26.",
  "Sample placeholder summary for week 26. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 26. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 26)": "Reper exemplu A (săptămâna 26)",
  "Sample milestone B (week 26)": "Reper exemplu B (săptămâna 26)",
  "Sample physical note (week 26)": "Notă fizică exemplu (săptămâna 26)",
  "Sample emotional note (week 26)": "Notă emoțională exemplu (săptămâna 26)",
  "Sample dad action 1 (week 26)": "Acțiune exemplu 1 pentru tata (săptămâna 26)",
  "Sample dad action 2 (week 26)": "Acțiune exemplu 2 pentru tata (săptămâna 26)",
  "Sample dad action 3 (week 26)": "Acțiune exemplu 3 pentru tata (săptămâna 26)",
  "Sample heads-up text for week 26.": "Text exemplu „atenție la” pentru săptămâna 26.",
  "Sample tip for dads in week 26.": "Sfat exemplu pentru tați, săptămâna 26.",
  "Highball glass": "Highball glass",
  "Sample size comparison for week 27.": "Comparație de mărime (exemplu) pentru săptămâna 27.",
  "Sample placeholder summary for week 27. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 27. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 27)": "Reper exemplu A (săptămâna 27)",
  "Sample milestone B (week 27)": "Reper exemplu B (săptămâna 27)",
  "Sample physical note (week 27)": "Notă fizică exemplu (săptămâna 27)",
  "Sample emotional note (week 27)": "Notă emoțională exemplu (săptămâna 27)",
  "Sample dad action 1 (week 27)": "Acțiune exemplu 1 pentru tata (săptămâna 27)",
  "Sample dad action 2 (week 27)": "Acțiune exemplu 2 pentru tata (săptămâna 27)",
  "Sample dad action 3 (week 27)": "Acțiune exemplu 3 pentru tata (săptămâna 27)",
  "Sample heads-up text for week 27.": "Text exemplu „atenție la” pentru săptămâna 27.",
  "Sample tip for dads in week 27.": "Sfat exemplu pentru tați, săptămâna 27.",
  "Sample size comparison for week 28.": "Comparație de mărime (exemplu) pentru săptămâna 28.",
  "Sample placeholder summary for week 28. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 28. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 28)": "Reper exemplu A (săptămâna 28)",
  "Sample milestone B (week 28)": "Reper exemplu B (săptămâna 28)",
  "Sample physical note (week 28)": "Notă fizică exemplu (săptămâna 28)",
  "Sample emotional note (week 28)": "Notă emoțională exemplu (săptămâna 28)",
  "Sample dad action 1 (week 28)": "Acțiune exemplu 1 pentru tata (săptămâna 28)",
  "Sample dad action 2 (week 28)": "Acțiune exemplu 2 pentru tata (săptămâna 28)",
  "Sample dad action 3 (week 28)": "Acțiune exemplu 3 pentru tata (săptămâna 28)",
  "Sample heads-up text for week 28.": "Text exemplu „atenție la” pentru săptămâna 28.",
  "Sample tip for dads in week 28.": "Sfat exemplu pentru tați, săptămâna 28.",
  "Sample size comparison for week 29.": "Comparație de mărime (exemplu) pentru săptămâna 29.",
  "Sample placeholder summary for week 29. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 29. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 29)": "Reper exemplu A (săptămâna 29)",
  "Sample milestone B (week 29)": "Reper exemplu B (săptămâna 29)",
  "Sample physical note (week 29)": "Notă fizică exemplu (săptămâna 29)",
  "Sample emotional note (week 29)": "Notă emoțională exemplu (săptămâna 29)",
  "Sample dad action 1 (week 29)": "Acțiune exemplu 1 pentru tata (săptămâna 29)",
  "Sample dad action 2 (week 29)": "Acțiune exemplu 2 pentru tata (săptămâna 29)",
  "Sample dad action 3 (week 29)": "Acțiune exemplu 3 pentru tata (săptămâna 29)",
  "Sample heads-up text for week 29.": "Text exemplu „atenție la” pentru săptămâna 29.",
  "Sample tip for dads in week 29.": "Sfat exemplu pentru tați, săptămâna 29.",
  "Sample size comparison for week 30.": "Comparație de mărime (exemplu) pentru săptămâna 30.",
  "Sample placeholder summary for week 30. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 30. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 30)": "Reper exemplu A (săptămâna 30)",
  "Sample milestone B (week 30)": "Reper exemplu B (săptămâna 30)",
  "Sample physical note (week 30)": "Notă fizică exemplu (săptămâna 30)",
  "Sample emotional note (week 30)": "Notă emoțională exemplu (săptămâna 30)",
  "Sample dad action 1 (week 30)": "Acțiune exemplu 1 pentru tata (săptămâna 30)",
  "Sample dad action 2 (week 30)": "Acțiune exemplu 2 pentru tata (săptămâna 30)",
  "Sample dad action 3 (week 30)": "Acțiune exemplu 3 pentru tata (săptămâna 30)",
  "Sample heads-up text for week 30.": "Text exemplu „atenție la” pentru săptămâna 30.",
  "Sample tip for dads in week 30.": "Sfat exemplu pentru tați, săptămâna 30.",
  "Sample size comparison for week 31.": "Comparație de mărime (exemplu) pentru săptămâna 31.",
  "Sample placeholder summary for week 31. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 31. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 31)": "Reper exemplu A (săptămâna 31)",
  "Sample milestone B (week 31)": "Reper exemplu B (săptămâna 31)",
  "Sample physical note (week 31)": "Notă fizică exemplu (săptămâna 31)",
  "Sample emotional note (week 31)": "Notă emoțională exemplu (săptămâna 31)",
  "Sample dad action 1 (week 31)": "Acțiune exemplu 1 pentru tata (săptămâna 31)",
  "Sample dad action 2 (week 31)": "Acțiune exemplu 2 pentru tata (săptămâna 31)",
  "Sample dad action 3 (week 31)": "Acțiune exemplu 3 pentru tata (săptămâna 31)",
  "Sample heads-up text for week 31.": "Text exemplu „atenție la” pentru săptămâna 31.",
  "Sample tip for dads in week 31.": "Sfat exemplu pentru tați, săptămâna 31.",
  "Sample size comparison for week 32.": "Comparație de mărime (exemplu) pentru săptămâna 32.",
  "Sample placeholder summary for week 32. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 32. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 32)": "Reper exemplu A (săptămâna 32)",
  "Sample milestone B (week 32)": "Reper exemplu B (săptămâna 32)",
  "Sample physical note (week 32)": "Notă fizică exemplu (săptămâna 32)",
  "Sample emotional note (week 32)": "Notă emoțională exemplu (săptămâna 32)",
  "Sample dad action 1 (week 32)": "Acțiune exemplu 1 pentru tata (săptămâna 32)",
  "Sample dad action 2 (week 32)": "Acțiune exemplu 2 pentru tata (săptămâna 32)",
  "Sample dad action 3 (week 32)": "Acțiune exemplu 3 pentru tata (săptămâna 32)",
  "Sample heads-up text for week 32.": "Text exemplu „atenție la” pentru săptămâna 32.",
  "Sample tip for dads in week 32.": "Sfat exemplu pentru tați, săptămâna 32.",
  "Hurricane glass": "Hurricane glass",
  "Sample size comparison for week 33.": "Comparație de mărime (exemplu) pentru săptămâna 33.",
  "Sample placeholder summary for week 33. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 33. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 33)": "Reper exemplu A (săptămâna 33)",
  "Sample milestone B (week 33)": "Reper exemplu B (săptămâna 33)",
  "Sample physical note (week 33)": "Notă fizică exemplu (săptămâna 33)",
  "Sample emotional note (week 33)": "Notă emoțională exemplu (săptămâna 33)",
  "Sample dad action 1 (week 33)": "Acțiune exemplu 1 pentru tata (săptămâna 33)",
  "Sample dad action 2 (week 33)": "Acțiune exemplu 2 pentru tata (săptămâna 33)",
  "Sample dad action 3 (week 33)": "Acțiune exemplu 3 pentru tata (săptămâna 33)",
  "Sample heads-up text for week 33.": "Text exemplu „atenție la” pentru săptămâna 33.",
  "Sample tip for dads in week 33.": "Sfat exemplu pentru tați, săptămâna 33.",
  "Sample size comparison for week 34.": "Comparație de mărime (exemplu) pentru săptămâna 34.",
  "Sample placeholder summary for week 34. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 34. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 34)": "Reper exemplu A (săptămâna 34)",
  "Sample milestone B (week 34)": "Reper exemplu B (săptămâna 34)",
  "Sample physical note (week 34)": "Notă fizică exemplu (săptămâna 34)",
  "Sample emotional note (week 34)": "Notă emoțională exemplu (săptămâna 34)",
  "Sample dad action 1 (week 34)": "Acțiune exemplu 1 pentru tata (săptămâna 34)",
  "Sample dad action 2 (week 34)": "Acțiune exemplu 2 pentru tata (săptămâna 34)",
  "Sample dad action 3 (week 34)": "Acțiune exemplu 3 pentru tata (săptămâna 34)",
  "Sample heads-up text for week 34.": "Text exemplu „atenție la” pentru săptămâna 34.",
  "Sample tip for dads in week 34.": "Sfat exemplu pentru tați, săptămâna 34.",
  "Sample size comparison for week 35.": "Comparație de mărime (exemplu) pentru săptămâna 35.",
  "Sample placeholder summary for week 35. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 35. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 35)": "Reper exemplu A (săptămâna 35)",
  "Sample milestone B (week 35)": "Reper exemplu B (săptămâna 35)",
  "Sample physical note (week 35)": "Notă fizică exemplu (săptămâna 35)",
  "Sample emotional note (week 35)": "Notă emoțională exemplu (săptămâna 35)",
  "Sample dad action 1 (week 35)": "Acțiune exemplu 1 pentru tata (săptămâna 35)",
  "Sample dad action 2 (week 35)": "Acțiune exemplu 2 pentru tata (săptămâna 35)",
  "Sample dad action 3 (week 35)": "Acțiune exemplu 3 pentru tata (săptămâna 35)",
  "Sample heads-up text for week 35.": "Text exemplu „atenție la” pentru săptămâna 35.",
  "Sample tip for dads in week 35.": "Sfat exemplu pentru tați, săptămâna 35.",
  "Sample size comparison for week 36.": "Comparație de mărime (exemplu) pentru săptămâna 36.",
  "Sample placeholder summary for week 36. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 36. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 36)": "Reper exemplu A (săptămâna 36)",
  "Sample milestone B (week 36)": "Reper exemplu B (săptămâna 36)",
  "Sample physical note (week 36)": "Notă fizică exemplu (săptămâna 36)",
  "Sample emotional note (week 36)": "Notă emoțională exemplu (săptămâna 36)",
  "Sample dad action 1 (week 36)": "Acțiune exemplu 1 pentru tata (săptămâna 36)",
  "Sample dad action 2 (week 36)": "Acțiune exemplu 2 pentru tata (săptămâna 36)",
  "Sample dad action 3 (week 36)": "Acțiune exemplu 3 pentru tata (săptămâna 36)",
  "Sample heads-up text for week 36.": "Text exemplu „atenție la” pentru săptămâna 36.",
  "Sample tip for dads in week 36.": "Sfat exemplu pentru tați, săptămâna 36.",
  "Sample size comparison for week 37.": "Comparație de mărime (exemplu) pentru săptămâna 37.",
  "Sample placeholder summary for week 37. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 37. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 37)": "Reper exemplu A (săptămâna 37)",
  "Sample milestone B (week 37)": "Reper exemplu B (săptămâna 37)",
  "Sample physical note (week 37)": "Notă fizică exemplu (săptămâna 37)",
  "Sample emotional note (week 37)": "Notă emoțională exemplu (săptămâna 37)",
  "Sample dad action 1 (week 37)": "Acțiune exemplu 1 pentru tata (săptămâna 37)",
  "Sample dad action 2 (week 37)": "Acțiune exemplu 2 pentru tata (săptămâna 37)",
  "Sample dad action 3 (week 37)": "Acțiune exemplu 3 pentru tata (săptămâna 37)",
  "Sample heads-up text for week 37.": "Text exemplu „atenție la” pentru săptămâna 37.",
  "Sample tip for dads in week 37.": "Sfat exemplu pentru tați, săptămâna 37.",
  "Heavy pint glass": "Heavy pint glass",
  "Sample size comparison for week 38.": "Comparație de mărime (exemplu) pentru săptămâna 38.",
  "Sample placeholder summary for week 38. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 38. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 38)": "Reper exemplu A (săptămâna 38)",
  "Sample milestone B (week 38)": "Reper exemplu B (săptămâna 38)",
  "Sample physical note (week 38)": "Notă fizică exemplu (săptămâna 38)",
  "Sample emotional note (week 38)": "Notă emoțională exemplu (săptămâna 38)",
  "Sample dad action 1 (week 38)": "Acțiune exemplu 1 pentru tata (săptămâna 38)",
  "Sample dad action 2 (week 38)": "Acțiune exemplu 2 pentru tata (săptămâna 38)",
  "Sample dad action 3 (week 38)": "Acțiune exemplu 3 pentru tata (săptămâna 38)",
  "Sample heads-up text for week 38.": "Text exemplu „atenție la” pentru săptămâna 38.",
  "Sample tip for dads in week 38.": "Sfat exemplu pentru tați, săptămâna 38.",
  "Sample size comparison for week 39.": "Comparație de mărime (exemplu) pentru săptămâna 39.",
  "Sample placeholder summary for week 39. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 39. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 39)": "Reper exemplu A (săptămâna 39)",
  "Sample milestone B (week 39)": "Reper exemplu B (săptămâna 39)",
  "Sample physical note (week 39)": "Notă fizică exemplu (săptămâna 39)",
  "Sample emotional note (week 39)": "Notă emoțională exemplu (săptămâna 39)",
  "Sample dad action 1 (week 39)": "Acțiune exemplu 1 pentru tata (săptămâna 39)",
  "Sample dad action 2 (week 39)": "Acțiune exemplu 2 pentru tata (săptămâna 39)",
  "Sample dad action 3 (week 39)": "Acțiune exemplu 3 pentru tata (săptămâna 39)",
  "Sample heads-up text for week 39.": "Text exemplu „atenție la” pentru săptămâna 39.",
  "Sample tip for dads in week 39.": "Sfat exemplu pentru tați, săptămâna 39.",
  "Sample size comparison for week 40.": "Comparație de mărime (exemplu) pentru săptămâna 40.",
  "Sample placeholder summary for week 40. Replace this with your own week-by-week content.": "Rezumat exemplu pentru săptămâna 40. Înlocuiește-l cu propriul conținut.",
  "Sample milestone A (week 40)": "Reper exemplu A (săptămâna 40)",
  "Sample milestone B (week 40)": "Reper exemplu B (săptămâna 40)",
  "Sample physical note (week 40)": "Notă fizică exemplu (săptămâna 40)",
  "Sample emotional note (week 40)": "Notă emoțională exemplu (săptămâna 40)",
  "Sample dad action 1 (week 40)": "Acțiune exemplu 1 pentru tata (săptămâna 40)",
  "Sample dad action 2 (week 40)": "Acțiune exemplu 2 pentru tata (săptămâna 40)",
  "Sample dad action 3 (week 40)": "Acțiune exemplu 3 pentru tata (săptămâna 40)",
  "Sample heads-up text for week 40.": "Text exemplu „atenție la” pentru săptămâna 40.",
  "Sample tip for dads in week 40.": "Sfat exemplu pentru tați, săptămâna 40."
};
